[project]
name = "minilogue-usb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyusb>=1.3.1",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]
