[project]
name = "preset-dump"
version = "0.1.0"
description = "Minilogue XD preset conversion service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.32.0",
    "python-multipart>=0.0.12",
    "pytest>=8.4.1",
]
